### Day 3: Data Profiling and Data Quality Assessment

Objective:
The objective of this notebook is to profile the landslide datasets and assess their quality before performing data cleaning. This includes inspecting dataset dimensions, data types, missing values, and duplicate records.

1. Import Required Libraries

In this section, we import the Python libraries required for data loading and profiling. Pandas is used for data manipulation, while NumPy supports numerical operations.

In [1]:
import pandas as pd
import numpy as np

2. Load the Datasets

Load the Landslide Events and Emergency Response datasets into pandas DataFrames for further analysis.

In [2]:
df = pd.read_csv("Merged_Landslide_Data.csv")

3. Preview the Data

Display the first few rows of each dataset to understand the available features and verify that the data has been loaded correctly.

In [3]:
print("Lanslides Dataset")
display(df.head())

Lanslides Dataset

,Event_ID,Date,State,District,Latitude,Longitude,Season,Rainfall_mm,Elevation_m,Slope_Degree,...,Cranes,Relief_Camps,Evacuated_People,Aid_Amount_INR,Relief_Materials_Tons,Compensation_Provided,Recovery_Days,Power_Outage_Hours,Water_Supply_Disrupted,Communication_Disruption
0,LS-029431,2015-05-17,Manipur,Ukhrul,25.67865,94.21606,Pre-Monsoon,0.0,1374.0,NaN,...,0.0,0.0,0.0,0.0,0.0,No,1.0,0.0,No,No
1,LS-027751,2015-02-04,Himachal Pradesh,Kinnaur,30.88606,77.17932,Winter,12.2,917.2,45.7,...,0.0,0.0,9.0,0.0,0.0,No,1.0,0.0,No,No
2,LS-047783,2024-12-05,Jammu and Kashmir,Ramban,34.61433,74.51911,Winter,38.2,1023.6,25.0,...,0.0,0.0,8.0,0.0,0.0,No,1.0,0.0,No,No
3,LS-010499,2016-10-13,Nagaland,Phek,26.16441,94.18366,Post-Monsoon,NaN,797.8,42.5,...,0.0,0.0,8.0,0.0,0.0,No,0.0,0.0,No,No
4,LS-024748,2013-10-19,Uttarakhand,Chamoli,29.90420,79.92994,NaN,61.1,1063.9,41.1,...,NaN,0.0,19.0,0.0,0.0,No,2.0,0.0,No,No

4. Dataset Dimensions

Determine the total number of rows and columns present in each dataset. This provides a quick overview of the dataset size.

Task Covered: Profile row and column counts per file.

In [4]:
print("Events Dataset Shape:", df.shape)

print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Events Dataset Shape: (48108, 52)
Rows : 48108
Columns : 52

5. Dataset Information

Display dataset information including column names, data types, and non-null values using the .info() function.

In [5]:
print("Dataset Info")
df.info()

Dataset Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48108 entries, 0 to 48107
Data columns (total 52 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Event_ID                    48108 non-null  object
 1   Date                        47216 non-null  object
 2   State                       47212 non-null  object
 3   District                    46247 non-null  object
 4   Latitude                    47001 non-null  float64
 5   Longitude                   46973 non-null  float64
 6   Season                      47172 non-null  object
 7   Rainfall_mm                 45537 non-null  float64
 8   Elevation_m                 46618 non-null  float64
 9   Slope_Degree                46571 non-null  float64
 10  Soil_Type                   46146 non-null  object
 11  NDVI                        46535 non-null  float64
 12  Temperature_C               47149 non-null  float64
 13  Humidity                    47000 non-null  float64
 14  Distance_to_River_km        46693 non-null  float64
 15  Land_Use                    46183 non-null  object
 16  Historical_Landslide_Count  47100 non-null  float64
 17  Landslide_Occurred          47422 non-null  object
 18  Landslide_Risk              46618 non-null  object
 19  Casualties                  45934 non-null  float64
 20  Injured                     46486 non-null  float64
 21  Missing_Persons             46905 non-null  float64
 22  Families_Affected           46239 non-null  float64
 23  Population_Affected         46645 non-null  float64
 24  Houses_Damaged              45988 non-null  float64
 25  Roads_Blocked_km            45994 non-null  float64
 26  Bridges_Damaged             46419 non-null  float64
 27  Economic_Loss_INR           46132 non-null  float64
 28  Cropland_Damaged            46935 non-null  float64
 29  Livestock_Lost              46258 non-null  float64
 30  Response_ID                 48108 non-null  object
 31  Response_Time_Min           46553 non-null  float64
 32  Rescue_Duration_Hours       44493 non-null  float64
 33  Human_Resources_Deployed    45891 non-null  float64
 34  Rescue_Teams                45820 non-null  float64
 35  NDRF_Teams                  46282 non-null  float64
 36  SDRF_Teams                  46740 non-null  float64
 37  Volunteers                  46435 non-null  float64
 38  Ambulances                  47059 non-null  float64
 39  Helicopters                 45654 non-null  float64
 40  Excavators                  45751 non-null  float64
 41  JCB_Machines                45874 non-null  float64
 42  Cranes                      46971 non-null  float64
 43  Relief_Camps                45817 non-null  float64
 44  Evacuated_People            46720 non-null  float64
 45  Aid_Amount_INR              46623 non-null  float64
 46  Relief_Materials_Tons       46612 non-null  float64
 47  Compensation_Provided       47126 non-null  object
 48  Recovery_Days               46731 non-null  float64
 49  Power_Outage_Hours          47035 non-null  float64
 50  Water_Supply_Disrupted      47095 non-null  object
 51  Communication_Disruption    47140 non-null  object
dtypes: float64(39), object(13)
memory usage: 19.1+ MB

6. Inspect Data Types

Review the detected data type of each column to ensure numerical, categorical, and date fields are correctly identified.

Task Covered: Inspect data types for detected columns.

In [7]:
df.dtypes

Event_ID                       object
Date                           object
State                          object
District                       object
Latitude                      float64
Longitude                     float64
Season                         object
Rainfall_mm                   float64
Elevation_m                   float64
Slope_Degree                  float64
Soil_Type                      object
NDVI                          float64
Temperature_C                 float64
Humidity                      float64
Distance_to_River_km          float64
Land_Use                       object
Historical_Landslide_Count    float64
Landslide_Occurred             object
Landslide_Risk                 object
Casualties                    float64
Injured                       float64
Missing_Persons               float64
Families_Affected             float64
Population_Affected           float64
Houses_Damaged                float64
Roads_Blocked_km              float64
Bridges_Damaged               float64
Economic_Loss_INR             float64
Cropland_Damaged              float64
Livestock_Lost                float64
Response_ID                    object
Response_Time_Min             float64
Rescue_Duration_Hours         float64
Human_Resources_Deployed      float64
Rescue_Teams                  float64
NDRF_Teams                    float64
SDRF_Teams                    float64
Volunteers                    float64
Ambulances                    float64
Helicopters                   float64
Excavators                    float64
JCB_Machines                  float64
Cranes                        float64
Relief_Camps                  float64
Evacuated_People              float64
Aid_Amount_INR                float64
Relief_Materials_Tons         float64
Compensation_Provided          object
Recovery_Days                 float64
Power_Outage_Hours            float64
Water_Supply_Disrupted         object
Communication_Disruption       object
dtype: object

7. Summary Statistics

Generate descriptive statistics for both numerical and categorical columns to understand the distribution and characteristics of the data.

In [8]:
df.describe(include='all')

,Event_ID,Date,State,District,Latitude,Longitude,Season,Rainfall_mm,Elevation_m,Slope_Degree,...,Cranes,Relief_Camps,Evacuated_People,Aid_Amount_INR,Relief_Materials_Tons,Compensation_Provided,Recovery_Days,Power_Outage_Hours,Water_Supply_Disrupted,Communication_Disruption
count,48108,47216,47212,46247,47001.000000,46973.000000,47172,45537.000000,46618.000000,46571.000000,...,46971.000000,45817.000000,46720.000000,4.662300e+04,46612.000000,47126,46731.000000,47035.000000,47095,47140
unique,48108,7654,18,48,NaN,NaN,4,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2,2
top,LS-029431,2013-07-24,Odisha,Kalimpong,NaN,NaN,Monsoon,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,No,No
freq,1,18,2689,1335,NaN,NaN,15992,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,35914,NaN,NaN,38824,40918
mean,NaN,NaN,NaN,NaN,22.602287,84.007312,NaN,191.708136,1425.391952,32.034743,...,0.594537,0.899099,30.791524,9.502308e+05,4.004342,NaN,36.661381,5.847516,NaN,NaN
std,NaN,NaN,NaN,NaN,6.940321,7.817225,NaN,197.773049,845.601278,11.922846,...,1.199292,1.766998,37.376489,2.082115e+06,10.041602,NaN,66.462262,14.788741,NaN,NaN
min,NaN,NaN,NaN,NaN,8.110380,72.800280,NaN,0.000000,20.000000,2.000000,...,0.000000,0.000000,0.000000,-7.713100e+06,0.000000,NaN,0.000000,0.000000,NaN,NaN
25%,NaN,NaN,NaN,NaN,17.512090,76.149400,NaN,41.200000,800.600000,23.900000,...,0.000000,0.000000,7.000000,0.000000e+00,0.000000,NaN,1.000000,0.000000,NaN,NaN
50%,NaN,NaN,NaN,NaN,25.125250,82.997530,NaN,113.200000,1406.600000,32.000000,...,0.000000,0.000000,14.000000,0.000000e+00,0.000000,NaN,2.000000,0.000000,NaN,NaN
75%,NaN,NaN,NaN,NaN,27.298020,92.847080,NaN,298.700000,2003.375000,40.100000,...,0.000000,1.000000,49.000000,9.313155e+05,2.000000,NaN,39.000000,2.900000,NaN,NaN
max,NaN,NaN,NaN,NaN,34.799050,95.396360,NaN,1304.000000,5080.700000,82.600000,...,4.000000,13.000000,229.000000,2.894298e+07,107.400000,NaN,239.000000,157.200000,NaN,NaN

8. Missing Value Analysis

Identify the number of missing values present in each column. This helps determine which features require cleaning or imputation.

Task Covered: Log missing-value counts per column.

In [9]:
missing_events = df.isnull().sum()

missing_events

Event_ID                         0
Date                           892
State                          896
District                      1861
Latitude                      1107
Longitude                     1135
Season                         936
Rainfall_mm                   2571
Elevation_m                   1490
Slope_Degree                  1537
Soil_Type                     1962
NDVI                          1573
Temperature_C                  959
Humidity                      1108
Distance_to_River_km          1415
Land_Use                      1925
Historical_Landslide_Count    1008
Landslide_Occurred             686
Landslide_Risk                1490
Casualties                    2174
Injured                       1622
Missing_Persons               1203
Families_Affected             1869
Population_Affected           1463
Houses_Damaged                2120
Roads_Blocked_km              2114
Bridges_Damaged               1689
Economic_Loss_INR             1976
Cropland_Damaged              1173
Livestock_Lost                1850
Response_ID                      0
Response_Time_Min             1555
Rescue_Duration_Hours         3615
Human_Resources_Deployed      2217
Rescue_Teams                  2288
NDRF_Teams                    1826
SDRF_Teams                    1368
Volunteers                    1673
Ambulances                    1049
Helicopters                   2454
Excavators                    2357
JCB_Machines                  2234
Cranes                        1137
Relief_Camps                  2291
Evacuated_People              1388
Aid_Amount_INR                1485
Relief_Materials_Tons         1496
Compensation_Provided          982
Recovery_Days                 1377
Power_Outage_Hours            1073
Water_Supply_Disrupted        1013
Communication_Disruption       968
dtype: int64

9. Missing Value Percentage

Calculate the percentage of missing values in every column to evaluate the severity of incomplete data.

In [10]:
missing_percent = (df.isnull().mean()*100).round(2)

pd.DataFrame({
    "Missing %": missing_percent
})

                            Missing %
Event_ID                         0.00
Date                             1.85
State                            1.86
District                         3.87
Latitude                         2.30
Longitude                        2.36
Season                           1.95
Rainfall_mm                      5.34
Elevation_m                      3.10
Slope_Degree                     3.19
Soil_Type                        4.08
NDVI                             3.27
Temperature_C                    1.99
Humidity                         2.30
Distance_to_River_km             2.94
Land_Use                         4.00
Historical_Landslide_Count       2.10
Landslide_Occurred               1.43
Landslide_Risk                   3.10
Casualties                       4.52
Injured                          3.37
Missing_Persons                  2.50
Families_Affected                3.89
Population_Affected              3.04
Houses_Damaged                   4.41
Roads_Blocked_km                 4.39
Bridges_Damaged                  3.51
Economic_Loss_INR                4.11
Cropland_Damaged                 2.44
Livestock_Lost                   3.85
Response_ID                      0.00
Response_Time_Min                3.23
Rescue_Duration_Hours            7.51
Human_Resources_Deployed         4.61
Rescue_Teams                     4.76
NDRF_Teams                       3.80
SDRF_Teams                       2.84
Volunteers                       3.48
Ambulances                       2.18
Helicopters                      5.10
Excavators                       4.90
JCB_Machines                     4.64
Cranes                           2.36
Relief_Camps                     4.76
Evacuated_People                 2.89
Aid_Amount_INR                   3.09
Relief_Materials_Tons            3.11
Compensation_Provided            2.04
Recovery_Days                    2.86
Power_Outage_Hours               2.23
Water_Supply_Disrupted           2.11
Communication_Disruption         2.01

10. Duplicate Record Analysis (Event_ID)

Check for duplicate Event_ID values in the Landslide Events dataset to ensure each landslide event has a unique identifier.

Task Covered: Identify duplicates using Event_ID.

In [20]:
event_duplicates = df.duplicated(subset=['Event_ID'])

print("Duplicate Event_IDs:", event_duplicates.sum())

Duplicate Event_IDs: 0

11. Duplicate Record Analysis (Response_ID)

Check for duplicate Response_ID values in the Emergency Response dataset to verify that each response record is unique.

Task Covered: Identify duplicates using Response_ID.

In [21]:
response_duplicates = df.duplicated(subset=['Response_ID'])

print("Duplicate Response_IDs:", response_duplicates.sum())

Duplicate Response_IDs: 0

12. Complete Duplicate Rows

Identify fully duplicated rows across each dataset to detect redundant records that may need removal during the cleaning phase.

In [13]:
print(df.duplicated().sum())

0

13. Unique Values Analysis

Count the number of unique values in each column to better understand feature diversity and detect potential anomalies.

In [14]:
df.nunique()

Event_ID                      48108
Date                           7654
State                            18
District                         48
Latitude                      46169
Longitude                     45933
Season                            4
Rainfall_mm                    8257
Elevation_m                   23008
Slope_Degree                    709
Soil_Type                         7
NDVI                           1005
Temperature_C                   548
Humidity                        789
Distance_to_River_km           1439
Land_Use                          7
Historical_Landslide_Count       13
Landslide_Occurred                2
Landslide_Risk                    4
Casualties                       18
Injured                          35
Missing_Persons                   8
Families_Affected               128
Population_Affected             292
Houses_Damaged                   61
Roads_Blocked_km               1363
Bridges_Damaged                   6
Economic_Loss_INR             13591
Cropland_Damaged                640
Livestock_Lost                   21
Response_ID                   48108
Response_Time_Min              2952
Rescue_Duration_Hours           219
Human_Resources_Deployed         95
Rescue_Teams                      8
NDRF_Teams                        6
SDRF_Teams                        8
Volunteers                      106
Ambulances                       12
Helicopters                       4
Excavators                       10
JCB_Machines                      8
Cranes                            5
Relief_Camps                     14
Evacuated_People                193
Aid_Amount_INR                13802
Relief_Materials_Tons           748
Compensation_Provided             2
Recovery_Days                   240
Power_Outage_Hours             1031
Water_Supply_Disrupted            2
Communication_Disruption          2
dtype: int64

14. Data Profiling Summary

Summarize the findings from the data profiling process, including:

Total rows and columns
Data types
Missing values
Duplicate IDs
Complete duplicate rows